### ISSUE TITLE
Crash when CafeBazaar not installed on API 17

### ISSUE THREAD

**Issue by r3za13** [PHELAT/Poolakey#3]
The app will crash when cafebazaar is not installed on the phone and connect method of Payment class being called.
Error description:
`java.lang.IllegalStateException: context.packageManager.queryIntentServices(it, 0) must not be null`
Library-Version: 1.0.0-alpha01
It occurred on Emulator Nexus 4 - API 17 but there is no such an error on an actual device with API 28

**Comment by PHELAT** [comment]
Thank you for reporting this issue, it will be fixed on the next release.

**Comment by PHELAT** [comment]
Fixed now in 1.0.0-alpha02
